apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: {{ .Values.service.ports.grpc.targetPort }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.ports.metrics.port }}
      targetPort: {{ .Values.service.ports.metrics.targetPort }}
    - name: syslog
      protocol: TCP
      port: {{ .Values.service.ports.syslog.port }}
      targetPort: {{ .Values.service.ports.syslog.targetPort }}